CRUD-SECOND-VERSION/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CRUD_SECOND_VERSION.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Position { get; set; }
        [Display(Name = "Department")]
        [ForeignKey("Department")]
        public int IdDep { get; set; }
        public virtual Department Department { get; set; }
    }
}

CRUD-SECOND-VERSION/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CRUD_SECOND_VERSION.Models
{
    public class EmployeeViewModel
    {

        public string Name { get; set; }
        
        public string Position { get; set; }
   
    }
}

CRUD-SECOND-VERSION/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRUD_SECOND_VERSION.Models;
using Excel;
using Microsoft.Reporting.WebForms;
using OfficeOpenXml;
using PagedList;
using PagedList.Mvc;

using  Excel = Microsoft.Office.Interop.Excel;

namespace CRUD_SECOND_VERSION.Controllers
{
    public class EmployeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Employees
        public ActionResult Index(String search, string sortOrder, string currentFilter, int? page, int? pagesize)
        {
            var employees = db.Employees.Include(e => e.Department);
            //search
            //The search string value is received from the text box
            if (!String.IsNullOrEmpty(search))
            {
                employees = employees.Where(s => s.Name.Contains(search) ||
                s.Position.Contains(search) || s.Department.Name.Contains(search));
            }
            if (search != null)
            {
                page = 1;
                 
            }
            else
            {
                search = currentFilter;
            }
            List<SelectListItem> items = new List<SelectListItem>{          
            new SelectListItem{ Text="5", Value="5" },
             new SelectListItem{ Text="10", Value="10" },
            new SelectListItem{ Text="20", Value="20" },
             new SelectListItem{ Text="50", Value="50" },
            new SelectListItem{ Text="100", Value="100" }
        };

            ViewBag.CurrentFilter = search;
            ViewBag.CurrentSort = sortOrder;
            //The two ViewBag variables with the appropriate query string values
            //if the sortOrder parameter is null or empty, ViewBag.NameSortParm should be set to 
            //"name_desc"...  it should be set to an empty string.
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PositionSortParm = String.IsNullOrEmpty(sortOrder) ? "position_desc" : "";
            var emp = from s in db.Employees
                      select s;
            //After you click the Name heading, employees are 
            //displayed in descending name order.
            switch (sortOrder)
            {
                case "name_desc":
                    employees = employees.OrderByDescending(s => s.Name);
                    break;
                case "position_desc":
                    employees = employees.OrderByDescending(s => s.Position);
                    break;

                default:
                    employees = employees.OrderBy(s => s.Name);
                    break;
            }
            //pagination
            // 1) installing the PagedList.Mvc NuGet package
            // PagedList.Mvc is one of many good paging and sorting packages for ASP.NET MVC
            //The NuGet PagedList.Mvc package automatically installs the PagedList 
            //package as a dependency.

            //2) This code adds a page parameter, a current sort order parameter, and a current
            //filter parameter to the method signature
            int pageSize = pagesize ?? 5;       
            int pageNumber = (page ?? 1);
            ViewBag.pagesize = new SelectList(items, "value", "Text", pagesize);
            ViewBag.CurrentPageSize = pageSize;
  
            return View(employees.ToPagedList(pageNumber, pageSize));
        }

            // GET: Employees/Details/5
            public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.IdDep = new SelectList(db.Departments, "IdDep", "Name");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Position,IdDep")] Employee employee)
        {
            //var query = db.Employees.Select(c => new SelectListItem
            //{
            //    Value = c.Department.ImageUrl.ToString(),
            //    Text = c.Department.Name               
            //});

            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdDep = new SelectList(db.Departments,"IdDep", "Name", employee.IdDep);
            return View(employee);
           
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdDep = new SelectList(db.Departments, "IdDep", "Name", employee.IdDep);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Position,IdDep")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdDep = new SelectList(db.Departments, "IdDep", "Name", employee.IdDep);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult View ( int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return PartialView(employee);
        }

        public ActionResult CreateEmpView(Employee employee)
        {

            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdDep = new SelectList(db.Departments, "IdDep", "Name", employee.IdDep);
            return PartialView(employee);
           
        }
        public ActionResult DeleteEmpView(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return PartialView(employee);
        }
      
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // function ExportToExcel
        public void ExportToExcel()
        {
            var employees = db.Employees.Include(e => e.Department).ToList();
            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Report");
            ws.Cells["A1"].Value = "Communication";
            ws.Cells["B1"].Value = "Com1";

            ws.Cells["A2"].Value = "Report";
            ws.Cells["B2"].Value = "report1";

            ws.Cells["A3"].Value = "Date";
            ws.Cells["B2"].Value = string.Format("{0:dd MMMM yyyy} at {0:H: mm tt}", DateTimeOffset.Now);

            // start table 
            ws.Cells["A6"].Value = "ID";
            ws.Cells["B6"].Value = "Name";
           
            ws.Cells["D6"].Value = "Position";
            ws.Cells["E6"].Value = "Department Name";

            int rowStart = 7;
            foreach (var item in employees)
            {
                //if (item.Experience < 5)
                //{
                //    ws.Row(rowStart).Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                //    ws.Row(rowStart).Style.Fill.BackgroundColor.SetColor(ColorTranslator.FromHtml(string.Format("pink")));

                //}

                ws.Cells[string.Format("A{0}", rowStart)].Value = item.Id;

CRUD-SECOND-VERSION/Views/Employees/Create.cshtml
@model CRUD_SECOND_VERSION.Models.Employee
@{
    ViewBag.Title = "Create";
}
<br /><br /><br /><br />
<center><h2>Add a new employee</h2></center>
<br />
<h6>Please enter the required informations</h6>
<script src="~/Scripts/awem.js"></script>
<script src="~/Scripts/AwesomeMvc.js"></script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @*<div class="form-horizontal">*@

    <hr />
    <center>
        <table class="table table-info table-striped table-bordered ">
            <thead>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*<div class="form-group">*@
                <tr>
                    <th>
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    </th>

                    <th>
                        @*<div class="col-md-10">*@
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        @*</div>*@
                    </th>
                </tr>
            </thead>
            @*</div>*@
            <tbody>
                <tr>
                    <th>
                        @*<div class="form-group">*@
                        @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
                    </th>

                    <th>
                        @*<div class="col-md-10">*@
                        @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                        @*</div>*@
                        @*</div>*@
                    </th>
                </tr>

                <tr>
                    <th>
                        @Html.LabelFor(model => model.IdDep, "Department", htmlAttributes: new { @class = "control-label" })
                    </th>
                    <th>
                        @Html.DropDownList("IdDep", null, htmlAttributes: new { @class = "form-control" })
                    </th>

            </tbody>

           
        </table>

        <br />

      
        <br/>
        <br/>
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create employee" class="btn btn-outline-primary btn-lg button1" />
        </div>

    </center>
}
<div class="pull-right">
    <i class="fa fa-link" aria-hidden="true"></i>
    @Html.ActionLink("List of employees", "Index")
</div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CRUD-SECOND-VERSION/Views/Employees/CreateEmpView.cshtml
@model CRUD_SECOND_VERSION.Models.Employee


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <center>
                <h4 class="text-primary">Create employee</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 ">
                            @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IdDep, "IdDep", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("IdDep", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IdDep, "", new { @class = "text-danger" })
                        </div>
                    </div>
                
                    <br />
                    <br />

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-outline-primary btn-lg button1" style="width:50%" />
                        </div>
                    </div>
            </center>
        </div>
    }

CRUD-SECOND-VERSION/Views/Employees/Delete.cshtml
@model CRUD_SECOND_VERSION.Models.Employee

@{
    Layout = null;
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this employee?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
          Department
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @*<input type="submit" value="Delete" class="btn btn-default" />*@
        <input type="submit" value="Delete" class="btn btn-outline-danger btn-lg button1" style="width:50%" />

        @*@Html.ActionLink("Back to List", "Index")*@
    </div>
    }
</div>

CRUD-SECOND-VERSION/Views/Employees/Details.cshtml
@model CRUD_SECOND_VERSION.Models.Employee

@{
    ViewBag.Title = "Details";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/fontawesome/font-awesome.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
@*<script src="~/Content/jquery-ui.js"></script>*@
<center>


    @Html.DisplayNameFor(model => model.Name)
    <br />
    @Html.DisplayFor(model => model.Name)
    <br />
    Department
    <br />
    @Html.DisplayFor(model => model.Department.Name)
    <br />
    @Html.DisplayNameFor(model => model.Position)
    <br />
    @Html.DisplayFor(model => model.Position)
    <br />
   



    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</center>

CRUD-SECOND-VERSION/Views/Employees/Index.cshtml
@model PagedList.IPagedList<CRUD_SECOND_VERSION.Models.Employee>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{

    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> </title>
    <link rel="stylesheet" href="~/Content/CSS/emp.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <br />  <br />  <br />  <br />
    <h2>List of employees</h2>
    <br />
    @*@Html.ActionLink("Click here to add a new employee", "Create")*@
    <i class="fa fa-plus-circle" style=" color:deeppink;"></i>
    <a href="#" onclick="CreateEmpPopup()">Click here to add a new employee</a>
    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body" id="CreateEmpPopup">
                </div>
            </div>
        </div>
    </div>

    <br />  <br />
    @using (Html.BeginForm())

    {
        <p>
            @Html.TextBox("search", ViewBag.CurrentFilter as string)

            <input type="submit" value="Search" />
        </p>
    }


    <form id="form1" action=@Url.Action("Index","Employees") method="get">

        @Html.DropDownList("pagesize", (SelectList)ViewBag.PageSizeList, "--Select--")

    </form>
    <br />
    <table id="table1" class="table table-info table-striped table-bordered ">
        <thead>
            <tr>
                <th>
                    @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.ActionLink("Position", "Index", new { sortOrder = ViewBag.PositionSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    Department
                </th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tbody>
                <tr id="demo" onclick="changeColor(this)">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department.Name)
                    </td>
                    <td>


                        <i class="fas fa-edit" style=" color:darkgreen;" id="slide"></i>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.Id })*@

                        <a href="#" id="@item.Id" onclick="EditEmpPopup(@item.Id)" @*data-toggle="tooltip" data-placement="left"*@ @*title="Edit" class="edit"*@>Edit</a>
                        <div class="modal fade" id="myModal4">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <!-- Modal Header -->
                                    <div class="modal-header">

                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <!-- Modal body -->
                                    <div class="modal-body" id="EditEmpPopup">
                                    </div>
                                    <!-- Modal footer -->
                                </div>
                            </div>
                        </div>

                        <i class="far fa-address-card" style=" color:salmon;" id="slide1"></i>

                        <a href="#" id="@item.Id" onclick="DetailsPopup(@item.Id)" @*data-toggle="tooltip" data-placement="left"*@ @*title="Details" class="details"*@>Details</a>
                        <div class="modal fade" id="myModal2">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <!-- Modal Header -->
                                    <div class="modal-header">

                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <!-- Modal body -->
                                    <div class="modal-body" id="DetailsPopup">
                                    </div>

                                    <!-- Modal footer -->
                                    <div class="modal-footer">
                                        @*<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                        <i class="fa fa-window-close" aria-hidden="true" style=" color:red;" id="slide2"> </i>
                        @*@Html.ActionLink("Deletee", "Delete", new { id = item.Id })*@
                        <a href="#" id="@item.Id" onclick="DeleteEmpPopup(@item.Id)" @*data-toggle="tooltip" data-placement="left"*@ @*title="Delete" class="delete"*@>Delete</a>
                        <div class="modal fade" id="myModal3">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <!-- Modal Header -->
                                    <div class="modal-header">

                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <!-- Modal body -->
                                    <div class="modal-body" id="DeleteEmpPopup">
                                    </div>

                                    <!-- Modal footer -->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
            </tbody>
        }
    </table>
    <!-- export to excel    -->
    <a href="@Url.Action("ExportToExcel","Employees")">Export To Excel</a> <br />


    @Html.ActionLink("Export To Excel with report", "Reports", new { ReportType = "Excel" }) <br />
    @Html.ActionLink("Export To PDF", "Reports", new { ReportType = "PDF" }) <br />
    @Html.ActionLink("Export To Word", "Reports", new { ReportType = "Word" }) <br />
    @Html.ActionLink("Export To Image", "Reports", new { ReportType = "Image" })

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
                                                                            new
                                                                            {
                                                                                page,
                                                                                sortOrder = ViewBag.CurrentSort,
                                                                                currentFilter = ViewBag.CurrentFilter,
                                                                                pagesize = ViewBag.CurrentPageSize
                                                                            }))
</body>
</html>
<script type="text/javascript" src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js">
</script>
<script type="text/javascript">
    $(function () {
        // When onchange event occurs on <select id="pagesize">,
        // simply submit the form, which will submit the new pagesize value as querystring.
        if ($('#search').val() == '')
            $('#pagesize').on('change', function () {
                $('#form1').submit();
            });
    });
</script>
<script>
    function changeColor(o) {
        o.style.backgroundColor = (o.style.backgroundColor == 'aqua') ?
            ('transparent') : ('aqua');
    }
</script>

<script>
    var DetailsPopup = function (Id) {
        var url = "../Employees/View/" + Id;
        $('#DetailsPopup').load(url, function () {
            $('#myModal2').modal('show');
        })
    }

</script>
<script>
    var CreateEmpPopup = function () {
        var url = "../Employees/Create/";
        $('#CreateEmpPopup').load(url,
            function () {
            $('#myModal').modal('show');
        })
    }

</script>
<script>
    var DeleteEmpPopup = function (Id) {
        var url = "../Employees/Delete/" + Id;
        $('#DeleteEmpPopup').load(url, function () {
            $('#myModal3').modal('show');
        })
    }
</script>
<script>
    var EditEmpPopup = function (Id) {
        var url = "../Employees/Edit/" + Id;
        $('#EditEmpPopup').load(url, function () {
            $('#myModal4').modal('show');
        })
    }

</script>
<script>
    $(".edit").hide();
    $(".details").hide();
    $(".delete").hide();
    /* start toggle slide icon */
    $("#slide").click(function () {
        $(".edit").toggle(100);
    });

    $("#slide1").click(function () {
        $(" .details").toggle(100);
    });

    $("#slide2").click(function () {
        $(" .delete").toggle(100);
    });
</script>

CRUD-SECOND-VERSION/Views/Employees/Success.cshtml
@model CRUD_SECOND_VERSION.Models.Employee

@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>


<h3>List employees</h3>
<table>

    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Name)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.Position)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.Department.Name)
        </td>
    </tr>
    @foreach (var item in ViewBag.employees)
    {
    
    <tr id="demo" onclick="changeColor(this)">
        <td>
            @item.Name
        </td>
        <td>
            @item.Position
        </td>
        <td>
            @item.Department.Name
        </td>
    </tr>
                }
    </table>

CRUD-SECOND-VERSION/Views/Employees/Upload.cshtml
@model System.Data.DataTable
@using System.Data;

<h2>Upload File</h2>

@using (Html.BeginForm("Upload", "Employees", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="form-group">
        <input type="file" id="dataFile" name="upload" />
    </div>

    <div class="form-group">
        <input type="submit" value="Upload" class="btn btn-default" />
    </div>

    if (Model != null)
    {
        <table>
            <thead>
                <tr>
                    @foreach (DataColumn col in Model.Columns)
                    {
                        <th>@col.ColumnName</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.Rows)
                {
                    <tr>
                        @foreach (DataColumn col in Model.Columns)
                        {
                            <td>@row[col.ColumnName]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
}

CRUD-SECOND-VERSION/Views/Employees/View.cshtml
@model CRUD_SECOND_VERSION.Models.Employee

<div>
    <h4 class="text-primary">Employee details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
             Department        
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

    </dl>
</div>